### ISSUE TITLE
DD logo uit favicon

### ISSUE THREAD

**Issue by bacor** [rensbaardman/uva-referendum.nl#3]
Het D&D logo gebruiken we alleen voor communicatie van de commissie. De website is van de campagne commissie.

Misschien een leeg blokje gebruiken; rood op witte achtergrond?

**Comment by bacor** [comment]
Ah correctie: de site staat niet helemaal los van de commissie, dus het logo mag er best op. Maar misschien zou ik het blokje in de favicon zetten, dat staat namelijk op alle promotie en het logo niet.

**Comment by rensbaardman** [comment]
Ja, deze dingen had ik ook al overwogen. Note: op https://www.facebook.com/referendumdd wordt trouwens ook het commissie-logo gebruikt.
Maar dat blokje lijkt me ook mooier in zo'n kleine favicon. Bv. paars blokje met een 'V' erin?
